# Generated by Django 2.1.7 on 2019-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0002_auto_20190401_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
