# Generated by Django 2.2 on 2019-04-08 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubble', '0005_sell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sell',
            new_name='Item',
        ),
    ]
