# Generated by Django 2.2 on 2019-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0007_auto_20190408_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_auctio n.jpg', upload_to='auction'),
        ),
    ]
