# Generated by Django 2.2 on 2019-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0014_auto_20190408_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='null', upload_to='auction'),
        ),
    ]
