# Generated by Django 2.2 on 2019-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0019_auto_20190408_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
