# Generated by Django 2.2 on 2019-04-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0020_auto_20190409_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
